// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknownError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SigninInterfaceErrorReason_UNKNOWN_ERROR.String() && e.Code == 500
}

func ErrorUnknownError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, SigninInterfaceErrorReason_UNKNOWN_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SigninInterfaceErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, SigninInterfaceErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsPasswordIncorrect(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SigninInterfaceErrorReason_PASSWORD_INCORRECT.String() && e.Code == 401
}

func ErrorPasswordIncorrect(format string, args ...interface{}) *errors.Error {
	return errors.New(401, SigninInterfaceErrorReason_PASSWORD_INCORRECT.String(), fmt.Sprintf(format, args...))
}

func IsUserExistedError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SigninInterfaceErrorReason_USER_EXISTED_ERROR.String() && e.Code == 406
}

func ErrorUserExistedError(format string, args ...interface{}) *errors.Error {
	return errors.New(406, SigninInterfaceErrorReason_USER_EXISTED_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsRecordExisted(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SigninInterfaceErrorReason_RECORD_EXISTED.String() && e.Code == 406
}

func ErrorRecordExisted(format string, args ...interface{}) *errors.Error {
	return errors.New(406, SigninInterfaceErrorReason_RECORD_EXISTED.String(), fmt.Sprintf(format, args...))
}

func IsRecordNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == SigninInterfaceErrorReason_RECORD_NOT_FOUND.String() && e.Code == 404
}

func ErrorRecordNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, SigninInterfaceErrorReason_RECORD_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
