// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sign-in/app/virtualwallet/service/internal/biz"
	"sign-in/app/virtualwallet/service/internal/conf"
	"sign-in/app/virtualwallet/service/internal/data"
	"sign-in/app/virtualwallet/service/internal/server"
	"sign-in/app/virtualwallet/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	virtualWalletRepo := data.NewWalletRepo(dataData, logger)
	virtualWalletUsecase := biz.NewVirtualWalletUsecase(virtualWalletRepo, logger)
	virtualWalletService := service.NewVirtualWalletService(virtualWalletUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, virtualWalletService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
