// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/signin/admin/v1/signin_admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignInAdminServiceClient is the client API for SignInAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignInAdminServiceClient interface {
	GetSignInRecord(ctx context.Context, in *GetSignInRecordRequest, opts ...grpc.CallOption) (*GetSignInRecordReply, error)
}

type signInAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignInAdminServiceClient(cc grpc.ClientConnInterface) SignInAdminServiceClient {
	return &signInAdminServiceClient{cc}
}

func (c *signInAdminServiceClient) GetSignInRecord(ctx context.Context, in *GetSignInRecordRequest, opts ...grpc.CallOption) (*GetSignInRecordReply, error) {
	out := new(GetSignInRecordReply)
	err := c.cc.Invoke(ctx, "/api.signin.admin.v1.SignInAdminService/GetSignInRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignInAdminServiceServer is the server API for SignInAdminService service.
// All implementations must embed UnimplementedSignInAdminServiceServer
// for forward compatibility
type SignInAdminServiceServer interface {
	GetSignInRecord(context.Context, *GetSignInRecordRequest) (*GetSignInRecordReply, error)
	mustEmbedUnimplementedSignInAdminServiceServer()
}

// UnimplementedSignInAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSignInAdminServiceServer struct {
}

func (UnimplementedSignInAdminServiceServer) GetSignInRecord(context.Context, *GetSignInRecordRequest) (*GetSignInRecordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignInRecord not implemented")
}
func (UnimplementedSignInAdminServiceServer) mustEmbedUnimplementedSignInAdminServiceServer() {}

// UnsafeSignInAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignInAdminServiceServer will
// result in compilation errors.
type UnsafeSignInAdminServiceServer interface {
	mustEmbedUnimplementedSignInAdminServiceServer()
}

func RegisterSignInAdminServiceServer(s grpc.ServiceRegistrar, srv SignInAdminServiceServer) {
	s.RegisterService(&SignInAdminService_ServiceDesc, srv)
}

func _SignInAdminService_GetSignInRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignInRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignInAdminServiceServer).GetSignInRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.signin.admin.v1.SignInAdminService/GetSignInRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignInAdminServiceServer).GetSignInRecord(ctx, req.(*GetSignInRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignInAdminService_ServiceDesc is the grpc.ServiceDesc for SignInAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignInAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.signin.admin.v1.SignInAdminService",
	HandlerType: (*SignInAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSignInRecord",
			Handler:    _SignInAdminService_GetSignInRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/signin/admin/v1/signin_admin.proto",
}
