// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// VirtualWallet is the predicate function for virtualwallet builders.
type VirtualWallet func(*sql.Selector)
