// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"sign-in/app/reward/job/internal/conf"
	"sign-in/app/reward/job/internal/data"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(server *conf.Server, confData *conf.Data, logger log.Logger) (*data.RewardRepo, func(), error) {
	consumer := data.NewKafkaConsumer(confData)
	virtualWalletClient := data.NewWalletClient(confData)
	dataData, cleanup, err := data.NewData(consumer, virtualWalletClient, logger)
	if err != nil {
		return nil, nil, err
	}
	rewardRepo := data.NewRewardRepo(dataData, logger)
	return rewardRepo, func() {
		cleanup()
	}, nil
}
