// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sign-in/app/signin/interface/internal/biz"
	"sign-in/app/signin/interface/internal/conf"
	"sign-in/app/signin/interface/internal/data"
	"sign-in/app/signin/interface/internal/server"
	"sign-in/app/signin/interface/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	userServiceClient := data.NewUserClient(confData)
	recordServiceClient := data.NewRecordClient(confData)
	dataData, err := data.NewData(confData, logger, userServiceClient, recordServiceClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(userRepo, logger)
	recordRepo := data.NewRecordRepo(dataData, logger)
	signInUsecase := biz.NewSignInUsecase(recordRepo, logger)
	singInService := service.NewSingInService(authUsecase, signInUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, singInService, logger)
	grpcServer := server.NewGRPCServer(confServer, singInService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
