// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sign-in/app/signin/admin/internal/biz"
	"sign-in/app/signin/admin/internal/conf"
	"sign-in/app/signin/admin/internal/data"
	"sign-in/app/signin/admin/internal/server"
	"sign-in/app/signin/admin/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	recordServiceClient := data.NewRecordServiceClient(confData)
	dataData, err := data.NewData(recordServiceClient, logger)
	if err != nil {
		return nil, nil, err
	}
	userRecordRepo := data.NewUserRecordRepo(dataData, logger)
	userRecordUseCase := biz.NewUserRecordUseCase(userRecordRepo, logger)
	signInAdminService := service.NewSignInAdminServiceService(userRecordUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, signInAdminService, logger)
	grpcServer := server.NewGRPCServer(confServer, signInAdminService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
