// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sign-in/app/record/service/internal/biz"
	"sign-in/app/record/service/internal/conf"
	"sign-in/app/record/service/internal/data"
	"sign-in/app/record/service/internal/server"
	"sign-in/app/record/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	syncProducer := data.NewKafkaProducer(confData)
	dataData, cleanup, err := data.NewData(confData, client, syncProducer, logger)
	if err != nil {
		return nil, nil, err
	}
	recordRepo := data.NewRecordRepo(dataData, logger)
	recordUseCase := biz.NewRecordUseCase(recordRepo, logger)
	recordService := service.NewRecordService(recordUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, recordService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
