// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// VirtualWalletColumns holds the columns for the "virtual_wallet" table.
	VirtualWalletColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "balance", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// VirtualWalletTable holds the schema information for the "virtual_wallet" table.
	VirtualWalletTable = &schema.Table{
		Name:       "virtual_wallet",
		Columns:    VirtualWalletColumns,
		PrimaryKey: []*schema.Column{VirtualWalletColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "virtualwallet_user_id",
				Unique:  true,
				Columns: []*schema.Column{VirtualWalletColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		VirtualWalletTable,
	}
)

func init() {
	VirtualWalletTable.Annotation = &entsql.Annotation{
		Table: "virtual_wallet",
	}
}
