// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"sign-in/app/virtualwallet/service/internal/data/ent/migrate"

	"sign-in/app/virtualwallet/service/internal/data/ent/virtualwallet"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// VirtualWallet is the client for interacting with the VirtualWallet builders.
	VirtualWallet *VirtualWalletClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.VirtualWallet = NewVirtualWalletClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		VirtualWallet: NewVirtualWalletClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		VirtualWallet: NewVirtualWalletClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		VirtualWallet.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.VirtualWallet.Use(hooks...)
}

// VirtualWalletClient is a client for the VirtualWallet schema.
type VirtualWalletClient struct {
	config
}

// NewVirtualWalletClient returns a client for the VirtualWallet from the given config.
func NewVirtualWalletClient(c config) *VirtualWalletClient {
	return &VirtualWalletClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `virtualwallet.Hooks(f(g(h())))`.
func (c *VirtualWalletClient) Use(hooks ...Hook) {
	c.hooks.VirtualWallet = append(c.hooks.VirtualWallet, hooks...)
}

// Create returns a create builder for VirtualWallet.
func (c *VirtualWalletClient) Create() *VirtualWalletCreate {
	mutation := newVirtualWalletMutation(c.config, OpCreate)
	return &VirtualWalletCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of VirtualWallet entities.
func (c *VirtualWalletClient) CreateBulk(builders ...*VirtualWalletCreate) *VirtualWalletCreateBulk {
	return &VirtualWalletCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for VirtualWallet.
func (c *VirtualWalletClient) Update() *VirtualWalletUpdate {
	mutation := newVirtualWalletMutation(c.config, OpUpdate)
	return &VirtualWalletUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VirtualWalletClient) UpdateOne(vw *VirtualWallet) *VirtualWalletUpdateOne {
	mutation := newVirtualWalletMutation(c.config, OpUpdateOne, withVirtualWallet(vw))
	return &VirtualWalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VirtualWalletClient) UpdateOneID(id uuid.UUID) *VirtualWalletUpdateOne {
	mutation := newVirtualWalletMutation(c.config, OpUpdateOne, withVirtualWalletID(id))
	return &VirtualWalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for VirtualWallet.
func (c *VirtualWalletClient) Delete() *VirtualWalletDelete {
	mutation := newVirtualWalletMutation(c.config, OpDelete)
	return &VirtualWalletDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *VirtualWalletClient) DeleteOne(vw *VirtualWallet) *VirtualWalletDeleteOne {
	return c.DeleteOneID(vw.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *VirtualWalletClient) DeleteOneID(id uuid.UUID) *VirtualWalletDeleteOne {
	builder := c.Delete().Where(virtualwallet.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VirtualWalletDeleteOne{builder}
}

// Query returns a query builder for VirtualWallet.
func (c *VirtualWalletClient) Query() *VirtualWalletQuery {
	return &VirtualWalletQuery{
		config: c.config,
	}
}

// Get returns a VirtualWallet entity by its id.
func (c *VirtualWalletClient) Get(ctx context.Context, id uuid.UUID) (*VirtualWallet, error) {
	return c.Query().Where(virtualwallet.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VirtualWalletClient) GetX(ctx context.Context, id uuid.UUID) *VirtualWallet {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *VirtualWalletClient) Hooks() []Hook {
	return c.hooks.VirtualWallet
}
