// Code generated by entc, DO NOT EDIT.

package ent

import (
	"sign-in/app/virtualwallet/service/internal/data/ent/schema"
	"sign-in/app/virtualwallet/service/internal/data/ent/virtualwallet"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	virtualwalletFields := schema.VirtualWallet{}.Fields()
	_ = virtualwalletFields
	// virtualwalletDescBalance is the schema descriptor for balance field.
	virtualwalletDescBalance := virtualwalletFields[2].Descriptor()
	// virtualwallet.DefaultBalance holds the default value on creation for the balance field.
	virtualwallet.DefaultBalance = virtualwalletDescBalance.Default.(float64)
	// virtualwalletDescUpdatedAt is the schema descriptor for updated_at field.
	virtualwalletDescUpdatedAt := virtualwalletFields[4].Descriptor()
	// virtualwallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	virtualwallet.DefaultUpdatedAt = virtualwalletDescUpdatedAt.Default.(func() time.Time)
	// virtualwalletDescID is the schema descriptor for id field.
	virtualwalletDescID := virtualwalletFields[0].Descriptor()
	// virtualwallet.DefaultID holds the default value on creation for the id field.
	virtualwallet.DefaultID = virtualwalletDescID.Default.(func() uuid.UUID)
}
