// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sign-in/app/virtualwallet/service/internal/data/ent/predicate"
	"sign-in/app/virtualwallet/service/internal/data/ent/virtualwallet"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VirtualWalletDelete is the builder for deleting a VirtualWallet entity.
type VirtualWalletDelete struct {
	config
	hooks    []Hook
	mutation *VirtualWalletMutation
}

// Where appends a list predicates to the VirtualWalletDelete builder.
func (vwd *VirtualWalletDelete) Where(ps ...predicate.VirtualWallet) *VirtualWalletDelete {
	vwd.mutation.Where(ps...)
	return vwd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vwd *VirtualWalletDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vwd.hooks) == 0 {
		affected, err = vwd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VirtualWalletMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vwd.mutation = mutation
			affected, err = vwd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vwd.hooks) - 1; i >= 0; i-- {
			if vwd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vwd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vwd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (vwd *VirtualWalletDelete) ExecX(ctx context.Context) int {
	n, err := vwd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vwd *VirtualWalletDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: virtualwallet.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: virtualwallet.FieldID,
			},
		},
	}
	if ps := vwd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, vwd.driver, _spec)
}

// VirtualWalletDeleteOne is the builder for deleting a single VirtualWallet entity.
type VirtualWalletDeleteOne struct {
	vwd *VirtualWalletDelete
}

// Exec executes the deletion query.
func (vwdo *VirtualWalletDeleteOne) Exec(ctx context.Context) error {
	n, err := vwdo.vwd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{virtualwallet.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vwdo *VirtualWalletDeleteOne) ExecX(ctx context.Context) {
	vwdo.vwd.ExecX(ctx)
}
