// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/record/v1/record.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSignInInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User int64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetSignInInfoRequest) Reset() {
	*x = GetSignInInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignInInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignInInfoRequest) ProtoMessage() {}

func (x *GetSignInInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignInInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSignInInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{0}
}

func (x *GetSignInInfoRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

type SignInInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewardList    []float64 `protobuf:"fixed64,1,rep,packed,name=reward_list,json=rewardList,proto3" json:"reward_list,omitempty"`
	SignIndexList []bool    `protobuf:"varint,2,rep,packed,name=sign_index_list,json=signIndexList,proto3" json:"sign_index_list,omitempty"`
	IsSignToday   bool      `protobuf:"varint,3,opt,name=is_sign_today,json=isSignToday,proto3" json:"is_sign_today,omitempty"`
}

func (x *SignInInfoReply) Reset() {
	*x = SignInInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInInfoReply) ProtoMessage() {}

func (x *SignInInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInInfoReply.ProtoReflect.Descriptor instead.
func (*SignInInfoReply) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{1}
}

func (x *SignInInfoReply) GetRewardList() []float64 {
	if x != nil {
		return x.RewardList
	}
	return nil
}

func (x *SignInInfoReply) GetSignIndexList() []bool {
	if x != nil {
		return x.SignIndexList
	}
	return nil
}

func (x *SignInInfoReply) GetIsSignToday() bool {
	if x != nil {
		return x.IsSignToday
	}
	return false
}

type SignInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User int64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{2}
}

func (x *SignInRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

type GetUserSignInRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Day  []string `protobuf:"bytes,2,rep,name=day,proto3" json:"day,omitempty"`
}

func (x *GetUserSignInRecordRequest) Reset() {
	*x = GetUserSignInRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSignInRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSignInRecordRequest) ProtoMessage() {}

func (x *GetUserSignInRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSignInRecordRequest.ProtoReflect.Descriptor instead.
func (*GetUserSignInRecordRequest) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserSignInRecordRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *GetUserSignInRecordRequest) GetDay() []string {
	if x != nil {
		return x.Day
	}
	return nil
}

type UserRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day    string  `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Index  int32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Reward float64 `protobuf:"fixed64,3,opt,name=reward,proto3" json:"reward,omitempty"`
}

func (x *UserRecord) Reset() {
	*x = UserRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRecord) ProtoMessage() {}

func (x *UserRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRecord.ProtoReflect.Descriptor instead.
func (*UserRecord) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{4}
}

func (x *UserRecord) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *UserRecord) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UserRecord) GetReward() float64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

type GetUserSignInRecordReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserRecord []*UserRecord `protobuf:"bytes,1,rep,name=user_record,json=userRecord,proto3" json:"user_record,omitempty"`
}

func (x *GetUserSignInRecordReply) Reset() {
	*x = GetUserSignInRecordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSignInRecordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSignInRecordReply) ProtoMessage() {}

func (x *GetUserSignInRecordReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSignInRecordReply.ProtoReflect.Descriptor instead.
func (*GetUserSignInRecordReply) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserSignInRecordReply) GetUserRecord() []*UserRecord {
	if x != nil {
		return x.UserRecord
	}
	return nil
}

var File_api_record_v1_record_proto protoreflect.FileDescriptor

var file_api_record_v1_record_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x22, 0x2a, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x7e, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x49,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73,
	0x69, 0x67, 0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x08, 0x52, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x74,
	0x6f, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x53, 0x69,
	0x67, 0x6e, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x22, 0x23, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x49,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79,
	0x22, 0x4c, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x22, 0x56,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3a, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x32, 0x98, 0x02, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67,
	0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x46,
	0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x69, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x29, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x2b, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x76, 0x31, 0x50, 0x01, 0x5a, 0x18, 0x73, 0x69, 0x67, 0x6e, 0x2d, 0x69, 0x6e, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_record_v1_record_proto_rawDescOnce sync.Once
	file_api_record_v1_record_proto_rawDescData = file_api_record_v1_record_proto_rawDesc
)

func file_api_record_v1_record_proto_rawDescGZIP() []byte {
	file_api_record_v1_record_proto_rawDescOnce.Do(func() {
		file_api_record_v1_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_record_v1_record_proto_rawDescData)
	})
	return file_api_record_v1_record_proto_rawDescData
}

var file_api_record_v1_record_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_record_v1_record_proto_goTypes = []interface{}{
	(*GetSignInInfoRequest)(nil),       // 0: api.record.v1.GetSignInInfoRequest
	(*SignInInfoReply)(nil),            // 1: api.record.v1.SignInInfoReply
	(*SignInRequest)(nil),              // 2: api.record.v1.SignInRequest
	(*GetUserSignInRecordRequest)(nil), // 3: api.record.v1.GetUserSignInRecordRequest
	(*UserRecord)(nil),                 // 4: api.record.v1.UserRecord
	(*GetUserSignInRecordReply)(nil),   // 5: api.record.v1.GetUserSignInRecordReply
}
var file_api_record_v1_record_proto_depIdxs = []int32{
	4, // 0: api.record.v1.GetUserSignInRecordReply.user_record:type_name -> api.record.v1.UserRecord
	0, // 1: api.record.v1.RecordService.GetSignInInfo:input_type -> api.record.v1.GetSignInInfoRequest
	2, // 2: api.record.v1.RecordService.SignIn:input_type -> api.record.v1.SignInRequest
	3, // 3: api.record.v1.RecordService.GetUserSignInRecord:input_type -> api.record.v1.GetUserSignInRecordRequest
	1, // 4: api.record.v1.RecordService.GetSignInInfo:output_type -> api.record.v1.SignInInfoReply
	1, // 5: api.record.v1.RecordService.SignIn:output_type -> api.record.v1.SignInInfoReply
	5, // 6: api.record.v1.RecordService.GetUserSignInRecord:output_type -> api.record.v1.GetUserSignInRecordReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_record_v1_record_proto_init() }
func file_api_record_v1_record_proto_init() {
	if File_api_record_v1_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_record_v1_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignInInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_record_v1_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_record_v1_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_record_v1_record_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSignInRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_record_v1_record_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_record_v1_record_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSignInRecordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_record_v1_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_record_v1_record_proto_goTypes,
		DependencyIndexes: file_api_record_v1_record_proto_depIdxs,
		MessageInfos:      file_api_record_v1_record_proto_msgTypes,
	}.Build()
	File_api_record_v1_record_proto = out.File
	file_api_record_v1_record_proto_rawDesc = nil
	file_api_record_v1_record_proto_goTypes = nil
	file_api_record_v1_record_proto_depIdxs = nil
}
